export const responsePiata = {
  request: {
    type: "City",
    query: "Piata, Brazil",
    language: "en",
    unit: "m",
  },
  location: {
    name: "Piata",
    country: "Brazil",
    region: "Bahia",
    lat: "-13.150",
    lon: "-41.800",
    timezone_id: "America/Bahia",
    localtime: "2024-03-07 20:20",
    localtime_epoch: 1709842800,
    utc_offset: "-3.0",
  },
  current: {
    observation_time: "11:20 PM",
    temperature: 20,
    weather_code: 176,
    weather_icons: [
      "https://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
    ],
    weather_descriptions: ["Patchy rain nearby"],
    wind_speed: 17,
    wind_degree: 81,
    wind_dir: "E",
    pressure: 1017,
    precip: 0,
    humidity: 82,
    cloudcover: 77,
    feelslike: 20,
    uv_index: 1,
    visibility: 10,
    is_day: "no",
  },
};

export const responseSalvador = {
  request: {
    type: "City",
    query: "Salvador, Brazil",
    language: "en",
    unit: "m",
  },
  location: {
    name: "Salvador",
    country: "Brazil",
    region: "Bahia",
    lat: "-12.970",
    lon: "-38.510",
    timezone_id: "America/Bahia",
    localtime: "2024-03-07 20:20",
    localtime_epoch: 1709842800,
    utc_offset: "-3.0",
  },
  current: {
    observation_time: "11:20 PM",
    temperature: 25,
    weather_code: 116,
    weather_icons: [
      "https://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
    ],
    weather_descriptions: ["Partly cloudy"],
    wind_speed: 17,
    wind_degree: 81,
    wind_dir: "E",
    pressure: 1017,
    precip: 0,
    humidity: 82,
    cloudcover: 77,
    feelslike: 25,
    uv_index: 1,
    visibility: 10,
    is_day: "yes",
  },
};
