export const CODES_CONDITIONS = [
  {
    code: "395",
    description: "Neve moderada ou pesada em área com trovões",
    day_icon: "wsymbol_0012_heavy_snow_showers",
    night_icon: "wsymbol_0028_heavy_snow_showers_night",
  },
  {
    code: "392",
    description: "Neve leve em área com trovões",
    day_icon: "wsymbol_0016_thundery_showers",
    night_icon: "wsymbol_0032_thundery_showers_night",
  },
  {
    code: "389",
    description: "Chuva moderada ou pesada em área com trovões",
    day_icon: "wsymbol_0024_thunderstorms",
    night_icon: "wsymbol_0040_thunderstorms_night",
  },
  {
    code: "386",
    description: "Chuva fraca em área com trovões",
    day_icon: "wsymbol_0016_thundery_showers",
    night_icon: "wsymbol_0032_thundery_showers_night",
  },
  {
    code: "377",
    description: "Chuveiros moderados ou pesados de pellets de gelo",
    day_icon: "wsymbol_0021_cloudy_with_sleet",
    night_icon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: "374",
    description: "Chuveiros leves de pellets de gelo",
    day_icon: "wsymbol_0013_sleet_showers",
    night_icon: "wsymbol_0029_sleet_showers_night",
  },
  {
    code: "371",
    description: "Chuvas de neve moderadas ou pesadas",
    day_icon: "wsymbol_0012_heavy_snow_showers",
    night_icon: "wsymbol_0028_heavy_snow_showers_night",
  },
  {
    code: "368",
    description: "Chuvas de neve leves",
    day_icon: "wsymbol_0011_light_snow_showers",
    night_icon: "wsymbol_0027_light_snow_showers_night",
  },
  {
    code: "365",
    description: "Chuveiros de sleet moderados ou pesados",
    day_icon: "wsymbol_0013_sleet_showers",
    night_icon: "wsymbol_0029_sleet_showers_night",
  },
  {
    code: "362",
    description: "Chuveiros de sleet leves",
    day_icon: "wsymbol_0013_sleet_showers",
    night_icon: "wsymbol_0029_sleet_showers_night",
  },
  {
    code: "359",
    description: "Chuveiro de chuva torrencial",
    day_icon: "wsymbol_0018_cloudy_with_heavy_rain",
    night_icon: "wsymbol_0034_cloudy_with_heavy_rain_night",
  },
  {
    code: "356",
    description: "Chuva moderada ou pesada",
    day_icon: "wsymbol_0010_heavy_rain_showers",
    night_icon: "wsymbol_0026_heavy_rain_showers_night",
  },
  {
    code: "353",
    description: "Chuva leve",
    day_icon: "wsymbol_0009_light_rain_showers",
    night_icon: "wsymbol_0025_light_rain_showers_night",
  },
  {
    code: "350",
    description: "Pellets de gelo",
    day_icon: "wsymbol_0021_cloudy_with_sleet",
    night_icon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: "338",
    description: "Neve pesada",
    day_icon: "wsymbol_0020_cloudy_with_heavy_snow",
    night_icon: "wsymbol_0036_cloudy_with_heavy_snow_night",
  },
  {
    code: "335",
    description: "Neve pesada intermitente",
    day_icon: "wsymbol_0012_heavy_snow_showers",
    night_icon: "wsymbol_0028_heavy_snow_showers_night",
  },
  {
    code: "332",
    description: "Neve moderada",
    day_icon: "wsymbol_0020_cloudy_with_heavy_snow",
    night_icon: "wsymbol_0036_cloudy_with_heavy_snow_night",
  },
  {
    code: "329",
    description: "Neve moderada intermitente",
    day_icon: "wsymbol_0020_cloudy_with_heavy_snow",
    night_icon: "wsymbol_0036_cloudy_with_heavy_snow_night",
  },
  {
    code: "326",
    description: "Neve leve",
    day_icon: "wsymbol_0011_light_snow_showers",
    night_icon: "wsymbol_0027_light_snow_showers_night",
  },
  {
    code: "323",
    description: "Neve leve intermitente",
    day_icon: "wsymbol_0011_light_snow_showers",
    night_icon: "wsymbol_0027_light_snow_showers_night",
  },
  {
    code: "320",
    description: "Chuva moderada ou pesada de sleet",
    day_icon: "wsymbol_0019_cloudy_with_light_snow",
    night_icon: "wsymbol_0035_cloudy_with_light_snow_night",
  },
  {
    code: "317",
    description: "Sleet leve",
    day_icon: "wsymbol_0021_cloudy_with_sleet",
    night_icon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: "314",
    description: "Chuva congelante moderada ou pesada",
    day_icon: "wsymbol_0021_cloudy_with_sleet",
    night_icon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: "311",
    description: "Chuva congelante leve",
    day_icon: "wsymbol_0021_cloudy_with_sleet",
    night_icon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: "308",
    description: "Chuva pesada",
    day_icon: "wsymbol_0018_cloudy_with_heavy_rain",
    night_icon: "wsymbol_0034_cloudy_with_heavy_rain_night",
  },
  {
    code: "305",
    description: "Chuva pesada às vezes",
    day_icon: "wsymbol_0010_heavy_rain_showers",
    night_icon: "wsymbol_0026_heavy_rain_showers_night",
  },
  {
    code: "302",
    description: "Chuva moderada",
    day_icon: "wsymbol_0018_cloudy_with_heavy_rain",
    night_icon: "wsymbol_0034_cloudy_with_heavy_rain_night",
  },
  {
    code: "299",
    description: "Chuva moderada às vezes",
    day_icon: "wsymbol_0010_heavy_rain_showers",
    night_icon: "wsymbol_0026_heavy_rain_showers_night",
  },
  {
    code: "296",
    description: "Chuva leve",
    day_icon: "wsymbol_0018_cloudy_with_heavy_rain",
    night_icon: "wsymbol_0034_cloudy_with_heavy_rain_night",
  },
  {
    code: "293",
    description: "Chuva leve intermitente",
    day_icon: "wsymbol_0017_cloudy_with_light_rain",
    night_icon: "wsymbol_0033_cloudy_with_light_rain_night",
  },
  {
    code: "284",
    description: "Geada forte",
    day_icon: "wsymbol_0021_cloudy_with_sleet",
    night_icon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: "281",
    description: "Geada",
    day_icon: "wsymbol_0021_cloudy_with_sleet",
    night_icon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: "266",
    description: "Garoa leve",
    day_icon: "wsymbol_0017_cloudy_with_light_rain",
    night_icon: "wsymbol_0033_cloudy_with_light_rain_night",
  },
  {
    code: "263",
    description: "Garoa leve intermitente",
    day_icon: "wsymbol_0009_light_rain_showers",
    night_icon: "wsymbol_0025_light_rain_showers_night",
  },
  {
    code: "260",
    description: "Nevoeiro congelante",
    day_icon: "wsymbol_0007_fog",
    night_icon: "wsymbol_0007_fog",
  },
  {
    code: "248",
    description: "Nevoeiro",
    day_icon: "wsymbol_0007_fog",
    night_icon: "wsymbol_0007_fog",
  },
  {
    code: "230",
    description: "Tempestade de neve",
    day_icon: "wsymbol_0020_cloudy_with_heavy_snow",
    night_icon: "wsymbol_0036_cloudy_with_heavy_snow_night",
  },
  {
    code: "227",
    description: "Vento e neve",
    day_icon: "wsymbol_0019_cloudy_with_light_snow",
    night_icon: "wsymbol_0035_cloudy_with_light_snow_night",
  },
  {
    code: "200",
    description: "Rajadas de trovões nas proximidades",
    day_icon: "wsymbol_0016_thundery_showers",
    night_icon: "wsymbol_0032_thundery_showers_night",
  },
  {
    code: "185",
    description: "Garoa congelante intermitente nas proximidades",
    day_icon: "wsymbol_0021_cloudy_with_sleet",
    night_icon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: "182",
    description: "Sleet intermitente nas proximidades",
    day_icon: "wsymbol_0021_cloudy_with_sleet",
    night_icon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: "179",
    description: "Neve intermitente nas proximidades",
    day_icon: "wsymbol_0013_sleet_showers",
    night_icon: "wsymbol_0029_sleet_showers_night",
  },
  {
    code: "176",
    description: "Chuva intermitente nas proximidades",
    day_icon: "wsymbol_0009_light_rain_showers",
    night_icon: "wsymbol_0025_light_rain_showers_night",
  },
  {
    code: "143",
    description: "Névoa",
    day_icon: "wsymbol_0006_mist",
    night_icon: "wsymbol_0006_mist",
  },
  {
    code: "122",
    description: "Nublado",
    day_icon: "wsymbol_0004_black_low_cloud",
    night_icon: "wsymbol_0004_black_low_cloud",
  },
  {
    code: "119",
    description: "Nublado",
    day_icon: "wsymbol_0003_white_cloud",
    night_icon: "wsymbol_0004_black_low_cloud",
  },
  {
    code: "116",
    description: "Parcialmente Nublado",
    day_icon: "wsymbol_0002_sunny_intervals",
    night_icon: "wsymbol_0008_clear_sky_night",
  },
  {
    code: "113",
    description: "Céu Limpo/Sol",
    day_icon: "wsymbol_0001_sunny",
    night_icon: "wsymbol_0008_clear_sky_night",
  },
];
